name: Publish Preview Package
on: [push, pull_request]

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - run: bunx pkg-pr-new publish